### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by deptno** [deptno/dynamo#13]
This error occur by `dynamon` command installed  globally
not local

$ dynamon
v0.3.8 😈 Ready to work, open http://localhost:5500
TypeError: Object(...) is not a function
    at HomeComponent (/usr/local/lib/node_modules/dynamon/.next/server/static/uUQ9hmd2nmnBeuhEV7UcG/pages/index.js:3320:54)
    at c (/usr/local/lib/node_modules/dynamon/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:496)
    at Ga (/usr/local/lib/node_modules/dynamon/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:31:1)
    at a.render (/usr/local/lib/node_modules/dynamon/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:367)
    at a.read (/usr/local/lib/node_modules/dynamon/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:450)
    at renderToString (/usr/local/lib/node_modules/dynamon/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:82)
    at render (/usr/local/lib/node_modules/dynamon/node_modules/next-server/dist/server/render.js:39:16)
    at renderPage (/usr/local/lib/node_modules/dynamon/node_modules/next-server/dist/server/render.js:96:16)
    at Function.getInitialProps (/usr/local/lib/node_modules/dynamon/.next/server/static/uUQ9hmd2nmnBeuhEV7UcG/pages/_document.js:2086:25)
    at Function._callee$ (/usr/local/lib/node_modules/dynamon/.next/server/static/uUQ9hmd2nmnBeuhEV7UcG/pages/_document.js:3004:59)
  dynamon:backend/ws.js {"type":"ws connected"} +0ms
  dynamon:backend/ws.js {"type":"add endpoint","payload":{"name":"Dynamon Local DB","region":"dynamon","endpoint":"http://localhost:8000"}} +2ms

**Comment by lemon-li** [comment]
same error
